baseURL = 'https://thomasnesset.no/'
languageCode = 'en-us'
title = 'Thomas Nesset'
theme = 'PaperMod'

[params]
  author = "Thomas Nesset"
  description = "A sample Hugo blog with PaperMod theme"
  keywords = ["blog", "hugo", "static site"]
  
  [params.homeInfoParams]
    Title = "Welcome to My Blog"
    Content = "This is a sample Hugo static website built with the PaperMod theme."

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

[markup]
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true
